spring:
  data:
    mongodb:
      uri: mongodb+srv://wojtyczekPatryk:eWkRi6gfNQHMscRO@cluster0-jtrar.mongodb.net/test?retryWrites=true&w=majority
      database: ubooku_db
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 321289368387-bgjbtb5gocq7fbi2rqpp665p5asq2buc.apps.googleusercontent.com
            clientSecret: B5S2bx21Al1dkUuVzQVZ95hq
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 2130979020544743
            clientSecret: eac982de86d3a3ed286f97e132dd297f
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:4200/home